#!/bin/bash
# 🎯 Quick Help for Crypto Agent Forecaster Validation

echo "🚀 Crypto Agent Forecaster Validation - Quick Help"
echo "=================================================="
echo ""
echo "📊 Quick Start Commands:"
echo ""
echo "🔹 Basic Testing:"
echo "  uv run cli.py backtest --days 7 -c bitcoin -c ethereum    # Quick test"
echo "  uv run cli.py full-backtest --days 30                     # Full test"
echo ""
echo "🔹 Background Testing:"
echo "  ./run_background.sh screen quick-backtest"
echo "  ./run_background.sh nohup full-backtest"
echo ""
echo "📋 Available CLI Commands:"
echo ""
echo "🎯 Direct Commands:"
echo "  uv run cli.py backtest --days 7 -c bitcoin -c ethereum"
echo "  uv run cli.py full-backtest --days 30"
echo "  uv run cli.py quick-test"
echo "  uv run cli.py full-test"
echo "  uv run cli.py live --duration 12 --interval 2 -c bitcoin"
echo ""
echo "🎯 Background Commands:"
echo "  ./run_background.sh screen quick-backtest"
echo "  ./run_background.sh screen full-backtest"
echo "  ./run_background.sh screen full-test"
echo ""
echo "📊 Monitoring & Status:"
echo "  ./monitor.sh           # Real-time monitoring"
echo "  ./monitor.sh status    # Quick status check"
echo "  ./monitor.sh kill      # Stop all tests"
echo ""
echo "📈 Results & Reports:"
echo "  uv run cli.py status           # Recent validation results"
echo "  uv run cli.py report           # Generate HTML report"
echo ""
echo "🎯 Example Workflows:"
echo ""
echo "🔸 Quick Test (5 minutes):"
echo "   uv run cli.py backtest --days 7 -c bitcoin -c ethereum"
echo ""
echo "🔸 Background Full Test:"
echo "   ./run_background.sh screen full-test"
echo "   screen -r crypto-validation-[TAB]  # To reattach later"
echo ""
echo "🔸 Extended Backtest:"
echo "   uv run cli.py backtest --days 60 -c bitcoin -c ethereum -c solana"
echo ""
echo "🔸 Check Results:"
echo "   uv run cli.py status"
echo "   uv run cli.py report"
echo ""
echo "🎯 Common Parameters:"
echo ""
echo "📈 Cryptocurrencies (-c, --coins):"
echo "   bitcoin, ethereum, binancecoin, solana, cardano,"
echo "   avalanche, polygon, chainlink, polkadot, uniswap"
echo ""
echo "⏰ Time Periods (--days):"
echo "   7    = Quick test (recommended for first time)"
echo "   30   = Standard validation"
echo "   60+  = Extended analysis"
echo ""
echo "🎯 Intervals (--interval, hours):"
echo "   1    = Every hour (intensive)"
echo "   2    = Every 2 hours (standard)"
echo "   4    = Every 4 hours (light)"
echo ""
echo "💡 Pro Tips:"
echo ""
echo "🔹 Start Small:"
echo "   uv run cli.py backtest --days 7 -c bitcoin"
echo ""
echo "🔹 Use Screen for Long Tests:"
echo "   ./run_background.sh screen full-test"
echo "   # Detach with Ctrl+A, D"
echo "   # Reattach with: screen -r crypto-validation-[TAB]"
echo ""
echo "🔹 Monitor Progress:"
echo "   ./monitor.sh  # Real-time updates"
echo ""
echo "🔹 Check Results:"
echo "   uv run cli.py status  # Quick overview"
echo "   uv run cli.py report  # Detailed HTML report"
echo ""
echo "📖 For detailed documentation:"
echo "   cat README.md"
echo "   cat OVERVIEW.md"
echo ""
echo "❓ For full CLI help:"
echo "   uv run cli.py --help"
echo "   uv run cli.py backtest --help"
echo "   uv run cli.py live --help"
echo ""
echo "🐛 For troubleshooting:"
echo "   ./monitor.sh status"
echo ""
echo "🎯 Example: Quick Validation Test"
echo "=================================="
echo ""
echo "# 1. Quick test (5 minutes)"
echo "uv run cli.py backtest --days 7 -c bitcoin -c ethereum"
echo ""
echo "# 2. Check results" 
echo "uv run cli.py status"
echo ""
echo "# 3. Generate report"
echo "uv run cli.py report"
echo ""
echo "🎯 Example: Full Background Test"
echo "================================="
echo ""
echo "# 1. Start background test"
echo "./run_background.sh screen full-test"
echo ""
echo "# 2. Detach and continue working"
echo "# Press: Ctrl+A, then D"
echo ""
echo "# 3. Monitor progress (optional)"
echo "./monitor.sh"
echo ""
echo "# 4. Reattach to see results"
echo "screen -r crypto-validation-[TAB]"
echo ""
echo "✨ Happy forecasting! 🚀" 